// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZU3zpgHeXGVOvfWyCwlpZ4MOEqgppLk',
    appId: '1:766619242425:web:7f7cd61feffcbe57f47068',
    messagingSenderId: '766619242425',
    projectId: 'healtylife-87e82',
    authDomain: 'healtylife-87e82.firebaseapp.com',
    storageBucket: 'healtylife-87e82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVivvqvIvqsdFLRCpgouoLmtG5VE564s',
    appId: '1:766619242425:android:2a9d0bb5989b85fcf47068',
    messagingSenderId: '766619242425',
    projectId: 'healtylife-87e82',
    storageBucket: 'healtylife-87e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNbPcO0UtFnuIedFx-Xhdqm-rDPMhWEho',
    appId: '1:766619242425:ios:73d0decda816744ff47068',
    messagingSenderId: '766619242425',
    projectId: 'healtylife-87e82',
    storageBucket: 'healtylife-87e82.appspot.com',
    iosBundleId: 'com.example.healtyLife',
  );

}